CREATE TABLE CLIENTS (
  ID UUID PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  PHONE VARCHAR(255),
  MAIL VARCHAR(255),
  PASSPORT VARCHAR(255)
);
CREATE TABLE BANKS (
    ID UUID PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)
);
CREATE TABLE CLIENTS_BANKS (
    CLIENT_ID UUID NOT NULL,
    BANK_ID UUID NOT NULL
);
CREATE TABLE CREDITS (
    ID UUID PRIMARY KEY NOT NULL,
    LIMIT NUMERIC(20, 5),
    INTEREST NUMERIC(20, 5),
    BANK_ID UUID NOT NULL
);
CREATE TABLE CREDIT_OFFERS (
    ID UUID PRIMARY KEY NOT NULL,
    CREDIT_SUM NUMERIC(20, 5),
    CLIENT_ID UUID NOT NULL,
    CREDIT_ID UUID NOT NULL,
    BANK_ID UUID NOT NULL
);

CREATE TABLE PAYMENTS (
    ID UUID PRIMARY KEY NOT NULL,
    PAYMENT_DATE DATE,
    PAYMENT_SUM NUMERIC(20, 5),
    CREDIT_SUM NUMERIC(20, 5),
    INTEREST_SUM NUMERIC(20, 5),
    CREDIT_OFFER_ID UUID NOT NULL
);

ALTER TABLE CLIENTS_BANKS ADD CONSTRAINT CLIENT_ID_CONSTRAINT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID);
ALTER TABLE CLIENTS_BANKS ADD CONSTRAINT BANK_ID_CONSTRAINT FOREIGN KEY (BANK_ID) REFERENCES BANKS (ID);
ALTER TABLE CREDITS ADD CONSTRAINT CREDITS_BANK_ID_CONSTRAINT FOREIGN KEY (BANK_ID) REFERENCES BANKS (ID);
ALTER TABLE CREDIT_OFFERS ADD CONSTRAINT CO_CLIENT_ID_CONSTRAINT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID);
ALTER TABLE CREDIT_OFFERS ADD CONSTRAINT CO_CREDIT_ID_CONSTRAINT FOREIGN KEY (CREDIT_ID) REFERENCES CREDITS (ID);
ALTER TABLE CREDIT_OFFERS ADD CONSTRAINT CO_BANK_ID_CONSTRAINT FOREIGN KEY (BANK_ID) REFERENCES BANKS (ID);
ALTER TABLE PAYMENTS ADD CONSTRAINT CREDIT_OFFER_ID_CONSTRAINT FOREIGN KEY (CREDIT_OFFER_ID) REFERENCES CREDIT_OFFERS (ID);
